version: "3.9"
services:
  firewatch:
    build: .
    stdin_open: true
    container_name: firewatch-web-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "8082:8082"
    networks:
      - fire-app
  redis:
    image: redis:alpine
    container_name: ama-redis
    ports:
      - "6379:6379"
    networks:
      - fire-app
networks:
  fire-app:
    driver: bridge
